title: opendata.fit
email: contact@opendata.fit
description: >-
  opendata.fit - a data analysis & publication platform for the web
baseurl: ""
url: "https://opendata.fit"
github_username:  opendatafit

sass:
  load_paths:
    - "node_modules/opendatafit-common-styles"

plugins:
  - jekyll-seo-tag
